### ISSUE TITLE
Crash by adding attribution

### ISSUE THREAD

**Issue by atelyk** [RevenueCat/purchases-unity#34] opened 2020-11-11 18:48 UTC
1. Platform: iOS
    2. SDK version: 2.3.0
    3. OS version: not specific - iOS 12-14
    4. Xcode version: 11.7
    5. More then 300 users in 2 days

Recently released on iOS with updated RevenueCat version. I was not using attribution v2 and left deprecated methods usage for the next release to upgrade.
Crashlytic reported a lot of crashes.

**Fatal Exception: NSInvalidArgumentException**
Attempt to insert non-property list object **{** adgroup = "<null>"; "adgroup_id" = "<null>"; adset = "<null>"; "adset_id" = "<null>"; "af_click_lookback" = 7d; "af_cpi" = "<null>"; "af_siteid" = "<null>"; "af_status" = "Non-organic"; "af_sub1" = "<null>"; "af_sub2" = "<null>"; "af_sub3" = "<null>"; "af_sub4" = "<null>"; "af_sub5" = "<null>"; agency = "<null>"; campaign = None; "campaign_id" = "<null>"; "click_time" = "2020-11-11 17:12:29.165"; clickid = "{{{all_params}}}"; "cost_cents_USD" = 0; "engmnt_source" = "<null>"; "esp_name" = "<null>"; "http_referrer" = "<null>"; "install_time" = "2020-11-11 17:16:00.987"; "is_branded_link" = "<null>"; "is_first_launch" = 0; "is_universal_link" = "<null>"; iscache = 1; "match_type" = probabilistic; "media_source" = "*replaced*"; "orig_cost" = "0.0"; "rc_attribution_network_id" = "*replaced*"; "rc_idfa" = "*replaced*"; "rc_idfv" = "*replaced*"; "redirect_response_data" = "<null>"; "retargeting_conversion_type" = none; **}** 
for key com.revenuecat.userdefaults.attribution.71C3B32B-E61E-4B7F-AD5D-E6B39BA0A285

```
Fatal Exception: NSInvalidArgumentException				
0	CoreFoundation			__exceptionPreprocess	
1	libobjc.A.dylib			objc_exception_throw	
2	CoreFoundation			-[__NSCFString characterAtIndex:].cold.1	
3	CoreFoundation			_CFPrefsValidateValueForKey	
4	CoreFoundation			createDeepCopyOfValueForKey	
5	CoreFoundation			-[CFPrefsSource setValues:forKeys:count:copyValues:removeValuesForKeys:count:from:]	
6	CoreFoundation			-[CFPrefsSource setValues:forKeys:count:copyValues:from:]	
7	CoreFoundation			-[CFPrefsSource setValue:forKey:from:]	
8	CoreFoundation			__76-[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]_block_invoke	
9	CoreFoundation			__108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke	
10	CoreFoundation			normalizeQuintuplet	
11	CoreFoundation			-[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:]	
12	CoreFoundation			-[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]	
13	CoreFoundation			_CFPreferencesSetAppValueWithContainerAndConfiguration	
14	Foundation				-[NSUserDefaults(NSUserDefaults) setObject:forKey:]	
15	my_app				-[RCDeviceCache setLatestNetworkAndAdvertisingIdsSent:forAppUserID:] + 388 (RCDeviceCache.m:388)	
16	my_app				(Missing)	
17	my_app				(Missing)	
18	my_app				__69-[RCBackend postAttributionData:fromNetwork:forAppUserID:completion:]_block_invoke + 346 (RCBackend.m:346)	
19	my_app				(Missing)	
20	my_app				(Missing)	
21	CFNetwork			CFNetServiceBrowserSearchForServices	
22	CFNetwork			_CFHTTPMessageSetResponseProxyURL	
23	libdispatch.dylib		_dispatch_call_block_and_release	
24	libdispatch.dylib		_dispatch_client_callout	
25	libdispatch.dylib		_dispatch_lane_serial_drain$VARIANT$mp	
26	libdispatch.dylib		_dispatch_lane_invoke$VARIANT$mp	
27	libdispatch.dylib		_dispatch_workloop_worker_thread	
28	libsystem_pthread.dylib		_pthread_wqthread	
29	libsystem_pthread.dylib		start_wqthread	
```

Sorry, do not have steps, please let me know if the pasted call stack is not enough for the issue.

I assume that deprecated logic is broken.

**Comment by aboedo** [comment] 2020-11-11 19:08
hey @atelyk, thanks for reporting. 
We're actually aware of this bug, it happens when sending `NSNull` values to that method in that exact SDK version. 
It's fixed in the plugin's `2.3.1` version, so upgrading should fix it. I apologize for the inconvenience. 

For reference, the original bug was fixed here https://github.com/RevenueCat/purchases-ios/pull/359, and the fix was integrated into 2.3.1 https://github.com/RevenueCat/purchases-unity/releases/tag/2.3.1

**Comment by aboedo** [comment] 2020-11-11 19:09
I'm tentatively closing this issue since the bug is known & fixed in the latest version, but please let us know if you run into issues with 2.3.1.

**Closed by aboedo** 2020-11-11 19:09 UTC
Labels: bug

**Comment by atelyk** [comment] 2020-11-11 19:19
@aboedo 
Thanks a lot for the quick response in a stressful situation for me.
May you please address me to the steps to reproduce info or how is it affecting users description?
Since we've not faced any issues during the testing process.

**Comment by aboedo** [comment] 2020-11-11 19:34
It reproduces when you send something that doesn't meet iOS's `.plist` format.
The most common case I've seen is sending a dict with null values to the `AddAttribution` method, for example something like:

```c-sharp
var data = new AdjustData
        {
            adid = "test",
            campaign = null,
        };
        purchases.AddAttributionData(JsonUtility.ToJson(data), Purchases.AttributionNetwork.ADJUST, null);
```

There might be other ways to reproduce. In these cases, attribution does get sent correctly to the backend, but the SDK crashes right after the backend's response. 

Updating to 2.3.1 should allow you to send null values to `addAttribution`

**Comment by atelyk** [comment] 2020-11-12 16:58
Thank you a lot for the code snipped you've shared, it's the only way for us to test it. 
We are still trying to find user reproducibility steps, but with no luck.

Crashlytics created 2 more bugs with the same exception, but with different intro point. May you approve that it's the same issue caused previous plugin version?

```
Fatal Exception: NSInvalidArgumentException		
0	CoreFoundation	__exceptionPreprocess
1	libobjc.A.dylib	objc_exception_throw
2	CoreFoundation	-[NSCache init]
3	CoreFoundation	_CFPrefsValidateValueForKey
4	CoreFoundation	createDeepCopyOfValueForKey
5	CoreFoundation	-[CFPrefsSource setValues:forKeys:count:copyValues:removeValuesForKeys:count:from:]
6	CoreFoundation	-[CFPrefsSource setValues:forKeys:count:copyValues:from:]
7	CoreFoundation	-[CFPrefsSource setValue:forKey:from:]
8	CoreFoundation	__108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke
9	CoreFoundation	normalizeQuintuplet
10	CoreFoundation	-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]
11	CoreFoundation	-[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]
12	CoreFoundation	_CFPreferencesSetAppValueWithContainerAndConfiguration
13	Foundation	-[NSUserDefaults(NSUserDefaults) setObject:forKey:]
14	my_app		(Missing)
15	my_app		**__73-[RCAttributionFetcher postAttributionData:fromNetwork:forNetworkUserId:]_block_invoke + 158** (RCAttributionFetcher.m:158)
16	my_app		-[RCBackend handle:withResponse:error:errorHandler:] + 121 (RCBackend.m:121)
17	my_app		(Missing)
18	my_app		-[RCHTTPClient handleResponse:data:error:request:completionHandler:beginNextRequestWhenFinished:] + 140 (RCHTTPClient.m:140)
19	my_app		(Missing)
20	CFNetwork	__75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke
21	CFNetwork	__49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke
22	Foundation	__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
23	Foundation	-[NSBlockOperation main]
24	Foundation	-[__NSOperationInternal _start:]
25	Foundation	__NSOQSchedule_f
26	libdispatch.dylib	_dispatch_call_block_and_release
27	libdispatch.dylib	_dispatch_client_callout
28	libdispatch.dylib	_dispatch_continuation_pop$VARIANT$mp
29	libdispatch.dylib	_dispatch_async_redirect_invoke
30	libdispatch.dylib	_dispatch_root_queue_drain
31	libdispatch.dylib	_dispatch_worker_thread2
32	libsystem_pthread.dylib	_pthread_wqthread
33	libsystem_pthread.dylib	start_wqthread
```

```
Fatal Exception: NSInvalidArgumentException		
0	CoreFoundation	__exceptionPreprocess
1	libobjc.A.dylib	objc_exception_throw
2	CoreFoundation	-[__NSCFString characterAtIndex:].cold.1
3	CoreFoundation	_CFPrefsValidateValueForKey
4	CoreFoundation	createDeepCopyOfValueForKey
5	CoreFoundation	-[CFPrefsSource setValues:forKeys:count:copyValues:removeValuesForKeys:count:from:]
6	CoreFoundation	-[CFPrefsSource setValues:forKeys:count:copyValues:from:]
7	CoreFoundation	-[CFPrefsSource setValue:forKey:from:]
8	CoreFoundation	__76-[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]_block_invoke
9	CoreFoundation	__108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke
10	CoreFoundation	normalizeQuintuplet
11	CoreFoundation	-[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:]
12	CoreFoundation	-[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:]
13	CoreFoundation	_CFPreferencesSetAppValueWithContainerAndConfiguration
14	Foundation	-[NSUserDefaults(NSUserDefaults) setObject:forKey:]
15	my_app		(Missing)
16	my_app		(Missing)
17	my_app		(Missing)
18	my_app		__69-[RCBackend postAttributionData:fromNetwork:forAppUserID:completion:]_block_invoke + 346 (RCBackend.m:346)
19	my_app		(Missing)
20	my_app		__76-[RCHTTPClient performRequest:serially:path:body:headers:completionHandler:]_block_invoke + 96 (RCHTTPClient.m:96)
21	CFNetwork	CFNetServiceBrowserSearchForServices
22	CFNetwork	_CFHTTPMessageSetResponseProxyURL
23	libdispatch.dylib	_dispatch_call_block_and_release
24	libdispatch.dylib	_dispatch_client_callout
25	libdispatch.dylib	_dispatch_lane_serial_drain$VARIANT$armv81
26	libdispatch.dylib	_dispatch_lane_invoke$VARIANT$armv81
27	libdispatch.dylib	_dispatch_workloop_worker_thread
28	libsystem_pthread.dylib	_pthread_wqthread
29	libsystem_pthread.dylib	start_wqthread
```

**Comment by aboedo** [comment] 2020-11-12 17:00
yep, same bug. Crashlytics might just be logging it as a different thing if `AddAttributionData` is called from a different place

**Comment by atelyk** [comment] 2020-11-13 11:41
@aboedo , thank you a lot for your responses!
Actually looks like on one of our devices we've got this situation (no steps anyway). But with the new version app is crashed and looks like because of a memory issue after getting into infinity loop with the same messages added below. 
I couldn't find the place this message generated from, please address me if you know:

`[Purchases] - INFO: found 0 unsynced attributes for appUserID: 56865CAA-ED11-4D22-8040-D09AC8442C8E`

in another situation, it was these two messages repeated a **lot**:

```
[Purchases] - INFO: found 1 unsynced attributes for appUserID: DA279439-5581-4F23-827D-E3EDB840E473
[Purchases] - INFO: unsynced attributes: {
  uid = "Subscriber attribute: key: uid value: setTime: 2020-11-13 08:29:50 +0000";
}
```
iPad mini 2
iOS 12.4.8
The strange point in this situation is that previous builds, before RevenueCat update, also started crashing on this device due to the same infinity of messages.

**Comment by aboedo** [comment] 2020-11-13 14:23
I'm a bit surprised to hear about an infinite loop there... Thoughts: 
- the logs would be triggered if: 
- the app goes to / from background
- the app restores transactions
- a purchase is made

Any chance any of those is happening on an infinite loop? Maybe if there's an error and a retry mechanism?

**Comment by atelyk** [comment] 2020-11-13 15:05
Thank you for the additional info.
None of the mentioned logic shouldn't be in the loop, app is crashed just in the beginning, after retrieving purchases, previous transactions.
We are also confused since previous versions worked correctly on this device just yesterday morning.
I expect that maybe there is any logic that is retrying to send attributes data and this device triggering it somehow.

**Comment by aboedo** [comment] 2020-11-13 15:07
interesting. could you share crash logs for this? they might be able to help

**Comment by atelyk** [comment] 2020-11-13 18:57
Sorry for the long response, it looks like the device issue. I've failed to save first logs and from some time we stopped to retrieve an infinite list of _unsynced attributes_, but not stopped to retrieve crashes. So I have only [offline start of the app](https://gist.github.com/atelyk/bfd501e6c9cfe3160b2da6a43586e41d) with a lot of _unsynced attributes_

**Comment by atelyk** [comment] 2020-11-16 09:46
Just to close this topic – we've released new version, update to SDK 2.3.1 resolved our crashes, thank you for your support!
As for the device issue – today we started from trying new store version, everything worked correctly. Work with TestFlight has also repaired. Sorry, have no idea what was wrong with this device last week.

**Comment by aboedo** [comment] 2020-11-16 13:42
@atelyk I'm really glad to hear that! let me know if you run into any more issues. Have a great day!

**Comment by atelyk** [comment] 2020-11-19 13:22
@aboedo sorry for continuing into the same thread, but is it possible that RevenueCat started using any API that is specific for iOS 12?
We noticed that users with iOS 9-11 are not using the latest versions of our app which updated to SDK 2.3.0-2.3.1 (from 2.2.1)

**Comment by aboedo** [comment] 2020-11-19 14:08
@atelyk the SDK's deployment target is still set to iOS 9.0, no changes there. If there were, then as a developer you'd know because if the framework's deployment target is updated to a higher number than your app's deployment target, you'd have to update your deployment target or the app itself wouldn't compile.
So definitely check your app's deployment target to ensure that users on older iOS versions can still get updates, but there aren't any changes in RevenueCat that would cause that. 
Also, note that we do use some stuff that's specific to newer iOS versions, like introductory offers, but we enable them only for devices running the corresponding OS versions, without affecting older devices.

In my experience, users on older versions of iOS tend to also take longer to update app versions, and many of them will have automatic updates disabled for apps. So that may explain what you're seeing.

**Comment by atelyk** [comment] 2020-11-19 17:43
@aboedo yes, sure, it's still iOS 9.0 and we see that users installing the app (Appstore analytics), but they are not using it. And there are no any crashes tracked or any events generated from inside.
And one of theories I have is some conflict at the very start of the app
I've seen a bug report about 32bit device crash, but assume it crashes way later than the app start.
So currently I'm digging in the way to the new swift file and maybe some issues with build configuration (dependencies) after updating to 2.3.0. But I don't have such device, so asked in case you've noticed something.

**Comment by aboedo** [comment] 2020-11-19 17:54
Oh, I see. 
In case this helps your bug hunting, the 32-bit device crash could be triggered for users who've made at least one purchase, upon calling `checkIntroEligibility` or `restoreTransactions`. 
But the SDK should have been set up before any of those calls, so they'd probably be events generated before then.
I'd also expect that the crash would still show up on crash reporters. 
I'm not aware of any other issues with devices running older OS versions. 
We already have a fix for the 32-bit device crash, and it'll be ported to Unity very soon. 

Other than that, I can't think of anything sdk-related that might be causing a different level of usage on iOS 9-11

**Comment by atelyk** [comment] 2020-11-19 18:12
I've forgot to check Appstore crashes, and there is a bunch of them. But they are really short:
`Dyld Message: Library not loaded: @rpath/libswiftCore.dylib + 0`
and the second is 
`NO_CRASH_STACK + 0`
I received the first exception on simulator, but thought it's simulator specific issue, since couldn't fix it with all StackOverflow responses.

**Comment by aboedo** [comment] 2020-11-19 18:23
From the message, it doesn't look related to the `purchases-unity` sdk. 
Here are some thoughts, though, that may help you figure this out:

`Library not loaded` usually indicates a linker issue. This will result in a crash as soon as the app is loaded, so that would explain why users aren't actually using the app. 
I'm a bit suprised that the library causing it seems to be `swift`, or part of the Swift Core. My advice is to: 
- check your project's Swift settings in detail, to make sure that swift stuff works correctly
- test on both physical and simulator devices
- make sure that archiving your project also works, as archiving tends to surface lingering linker issues. 

Thoughts on stuff to try: 
- Try adding a swift file and seeing if it works correctly (specially when archiving)
- ensure that you have ALWAYS_EMBEDS_SWIFT_LIBRARIES, a Swift language version selected, and other swift settings
- ensure that the swift settings are set for both debug and release. 
- There are a few build flags that might help you, like `-ObjC`, `-all_load`. 

If all fails, try re-exporting the unity project to iOS to get a new version. Newer versions of the Unity Editor might also generate more modern configurations for iOS projects. 

Another thing that could help you, if possible, is to switch to static linking, although this might not work depending on your dependencies. `purchases-unity` should be compatible with static linking. 
Static linking forces the linking to happen before runtime, so that would ensure that any issues are solved before it gets to customers. 

Best of luck figuring this out!

**Comment by atelyk** [comment] 2020-11-20 18:05
Thank you for sharing ideas. I'm not confident with iOS build configuration, so at least I had a direction. What helped us is to add **Runpath Search Paths** value `@executable_path/Frameworks`
Maybe it's set up automatically with Unity 2019, but we need to stay on 2018 due to a lot of iOS 9 users.

**Comment by aboedo** [comment] 2020-11-20 18:20
@atelyk thanks for following up! that's good to know. I actually hadn't realized that newer versions of Unity forced the deployment target on iOS to a higher number. I'll make sure to test out older Unity Editors from now on.
